---
  # Take the first ec2 whose tag SwarmType is equal to "manager"
- hosts: _manager
  # this doesn't work - why? :
  # user: "{{ ansible_user }}"
  user: ubuntu
  # Use sudo for all tasks
  become: yes
  tasks:
    - include_tasks: tasks/install_docker.yml
    - include_tasks: tasks/init_swarm.yml

- hosts: _worker
  # Use sudo for all tasks
  user: ubuntu
  become: yes
  tasks:
    - include_tasks: tasks/install_docker.yml
    - include_tasks: tasks/join_worker_node.yml