# to run a playbook on a subset of servers, do e.g.:
# ansible-playbook -l _manager ping-playbook.yml
# or use _worker instead of _manager

---
- name: ping them all
  hosts: "all"

  user: ubuntu
  vars:
    ansible_ssh_private_key_file: "~/.ssh/ansible_tutorial.pem"
  tasks:
    - name: pinging
      ping: